CREATE TABLE IF NOT EXISTS public.migrations (
	id bigserial NOT NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	deleted_at timestamptz NULL,
	"name" text NOT NULL,
	"user" int8 NOT NULL,
	timezone text NULL,
	emails text NULL,
	src_type text NOT NULL,
	dest_type text NOT NULL,
	dest_bucket text NULL,
	src_bucket text NULL,
	src_files_path text NULL,
	src_s3_access_key text NULL,
	src_s3_secret_key text NULL,
	src_storage_directory text NULL,
	src_ssh_host text NULL,
	src_ssh_port text NULL,
	src_ssh_user text NULL,
	src_ssh_key text NULL,
	src_db_password text NULL,
	src_db_port text NULL,
	src_db_name text NULL,
	src_db_user text NULL,
	src_db_host text NULL,
	src_pod_label text NULL,
	src_container text NULL,
	src_pod_name text NULL,
	src_region text NULL,
    src_uri text NULL,
	dest_files_path text NULL,
	dest_s3_access_key text NULL,
	dest_s3_secret_key text NULL,
	dest_region text NULL,
	dest_storage_directory text NULL,
	dest_ssh_host text NULL,
	dest_ssh_port text NULL,
	dest_ssh_user text NULL,
	dest_ssh_key text NULL,
	dest_db_password text NULL,
	dest_db_port text NULL,
	dest_db_name text NULL,
	dest_db_user text NULL,
	dest_db_host text NULL,
	dest_pod_label text NULL,
	dest_container text NULL,
	dest_pod_name text NULL,
	dest_uri text NULL,
	CONSTRAINT migrations_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_migrations_deleted_at ON public.migrations USING btree (deleted_at);
