CREATE TABLE IF NOT EXISTS public.backups (
	id bigserial NOT NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	deleted_at timestamptz NULL,
	"name" text NOT NULL,
	frequency text NOT NULL,
	custom_frequency text NULL,
	"type" text NOT NULL,
	bucket text NULL,
	database_name text NULL,
	database_user text NULL,
	database_password text NULL,
	database_host text NULL,
	deployment text NULL,
	files_path text NULL,
	s3_access_key text NULL,
	s3_secret_key text NULL,
	storage_directory text NULL,
	retention int8 NULL,
	emails text NULL,
	"user" int8 NOT NULL,
	database_port text NULL,
	db_password text NULL,
	db_port text NULL,
	db_name text NULL,
	db_user text NULL,
	db_host text NULL,
	pod_label text NULL,
	container text NULL,
	pod_name text NULL,
	timezone text NULL,
	region text NULL,
	day_of_week int8 NULL,
	day_of_month int8 NULL,
	"time" text NULL,
	"month" int8 NULL,
	CONSTRAINT backups_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_backups_deleted_at ON public.backups USING btree (deleted_at);
